	<option value="0">Tutti gli annunci</option>
	<option value="0">----------------------</option>
	<option value="214"></option>
	<option value="296"></option>
	<option value="247"></option>
	<option value="215"> Attrezzature DJ</option>
	<option value="290"> Gioielli</option>
	<option value="29">Arte, Architettura & Fotografia</option>
	<option value="174">Attrezzatura Generale</option>
	<option value="133">Attrezzatura Video</option>
	<option value="209">Barattoli Vintage</option>
	<option value="318">Biciclette, pattini, o pattini</option>
	<option value="122">Carte Collezionabili</option>
	<option value="170">Cassette</option>
	<option value="245">Costumi</option>
	<option value="162">Dischi Laser</option>
	<option value="75">Filatelia</option>
	<option value="143">Generale</option>
	<option value="198">Hobbies</option>
	<option value="150">Infanzia</option>
	<option value="199">Marmo</option>
	<option value="2">Mondo Antico</option>
	<option value="72">Orologi</option>
	<option value="248">Ricambi auto</option>
	<option value="127">Software</option>
	<option value="157">Strumenti di Lavoro</option>
	<option value="113">Tabacco</option>
	<option value="210">Veicoli Vintage</option>
	<option value="68">Viaggi</option>
